
    - name: Check ostree status
      command: ostree admin status
      register: ostree_status

    - name: Check to see if an rpm-ostree transaction is currently running
      ansible.builtin.command: pgrep rpm-ostree
      register: ostree_status
      failed_when: ostree_status.rc == "999"  # Don't fail, regardless of return code

    - name: Cancel a current rpm-ostree update when an update is currently running.
      ansible.builtin.command: rpm-ostree cancel
      when: ostree_status.rc != 1

    - name: Install desired applications as layered packages
      community.general.rpm_ostree_pkg:
        name: "{{ item }}"
        state: present
      become: yes
      loop: "{{ layered_package_install }}"
    - debug:
        msg: "A reboot is required to complete installation / removal of these packages"
    - name: reboot if new stuff was installed
      reboot:
        reboot_timeout: 300
      become: yes
      when:
        - ostree_status.rc = 77