---
- name: Check if server is updating using ostree and ensure podman-compose is installed
  hosts: coreos
  become: true

  tasks:
    - name: Check ostree status
      command: ostree admin status
      register: ostree_status

    - name: Check to see if an rpm-ostree transaction is currently running
      ansible.builtin.command: pgrep rpm-ostree
      register: ostree_status
      failed_when: ostree_status.rc == "999"  # Don't fail, regardless of return code

    - name: Cancel a current rpm-ostree update when an update is currently running.
      ansible.builtin.command: rpm-ostree cancel
      when: ostree_status.rc != 1

    - name: Install desired applications as layered packages
      community.general.rpm_ostree_pkg:
        name: "{{ item }}"
        state: present
        become: yes
        become_method: sudo
        with_items: 
            - cockpit-ostree
            - cockpit-pcp
            - cockpit-podman
            - cockpit-storaged
            - cockpit-system
            - podman-compose
            - qemu-guest-agent
    - debug:
        msg: "A reboot is required to complete installation / removal of these packages"