  - name: Install desired applications as layered packages
  community.general.rpm_ostree_pkg:
    name: "podman-compose"
    state: present
    # apply_live: true  # This feature is not yet available
  become: yes
  become_method: sudo
  loop: "{{ layered_package_install }}"